---
authors:
  mdellweg:
    name: "Matthias Dellweg"
    description: "developer"
    avatar: "https://discourse.pulpproject.org/user_avatar/discourse.pulpproject.org/x9c4/120/12_2.png"
  dkliban:
    name: "Dennis Kliban"
    description: "developer"
    avatar: "https://discourse.pulpproject.org/user_avatar/discourse.pulpproject.org/dkliban/120/58_2.png"
...
