---
name: "Publish pulpproject.org"
on:
  schedule:
    - cron: "00 3 * * 1-5"
  workflow_dispatch:

defaults:
  run:
    working-directory: "pulp-docs"

jobs:
  build-docs:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          path: "pulp-docs"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"
      - name: "Build HTML site for pulpproject.org."
        run: |
          .github/workflows/scripts/build_all_docs.sh
      - name: "Upload documentation site"
        uses: "actions/upload-artifact@v4"
        with:
          name: "pulpproject.org.tar"
          path: "pulp-docs/pulpproject.org.tar"
          if-no-files-found: "error"

  publish-docs:
    runs-on: "ubuntu-latest"
    needs:
      - "build-docs"

    env:
      PULP_DOCS_KEY: "${{ secrets.PULP_DOCS_KEY }}"

    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 1
          path: "pulp-docs"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"

      - name: "Download built docs"
        uses: "actions/download-artifact@v4"
        with:
          name: "pulpproject.org.tar"
          path: "pulp-docs/"

      - name: "Publish docs to pulpproject.org"
        run: |
          .github/workflows/scripts/publish_all_docs.sh
...
